### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by Nonlimit** [seaneking/poststylus#10]
Hello!
Have a problem with background-image url(../images/1.jpg)
After compilition reported error with message no such file in directory
The structure of the project is on desctop
![1](https://cloud.githubusercontent.com/assets/11960153/10546086/a94a0be4-7434-11e5-84f3-fd25dd8eebac.PNG)
he is looking folder images on desktop not in my project/app/images/

I write a clear gulpfile with this code

'use strict'
let gulp = require('gulp'),
stylus = require('gulp-stylus');

gulp.task('css', () => {
return gulp.src('app/stylus/main.styl')
.pipe(stylus())
.pipe(gulp.dest('app/test'));
});

And stylus compiled same without errors

**Comment by seaneking** [comment]
what postcss plugins are you using with poststylus?

**Comment by Nonlimit** [comment]
I tested each plug-in and found a error in cssgrace

**Comment by seaneking** [comment]
alrighty, best follow it up with them then. I'll close this issue.
