### ISSUE TITLE
Breaking on existing sourcemap

### ISSUE THREAD

**Issue by FranzSkuffka** [seaneking/poststylus#14]
I use poststylus for [gulp-stylus-pipeline](https://github.com/FranzSkuffka/gulp-stylus-pipeline).
When I tried using this with [gulp-concat-sourcemap](https://github.com/mikach/gulp-concat-sourcemap) I had to realise the sourcemaps produced there are breaking poststylus.
Any idea if we could get this to work?

**Comment by seaneking** [comment]
How is it breaking? What's the stacktrace/error?
