### ISSUE TITLE
Webpack Example

### ISSUE THREAD

**Issue by Aweary** [seaneking/poststylus#16]
Any chance you could throw up an example of how you might use this with Webpack? Thanks!

**Comment by seaneking** [comment]
You'd just use the stylus loader as per usual, and use poststylus as a plugin, see: https://github.com/shama/stylus-loader#stylus-plugins. But yeah I'll put an example in the docs when I get a chance.

**Comment by seaneking** [comment]
Fixed in https://github.com/seaneking/poststylus/commit/366e27f489c93d38ee327970ad2126f0f47f7a95
