### ISSUE TITLE
Upgrade Stylus

### ISSUE THREAD

**Issue by corysimmons** [seaneking/poststylus#17]
Stylus <0.52 doesn't support non-standard @-rules.

Non standard @ rules are how global settings are set in PostCSS.

PostStylus not supporting non standard @ rules means PostStylus doesn't support users setting global vars from their stylesheets (like in [Lost](http://github.com/peterramsing/lost)).

They fixed this in Stylus .53 though https://github.com/stylus/stylus/issues/1900 so a quick upgrade should get it working. :+1: 

Thanks for the cool parser. :100:

**Comment by seaneking** [comment]
Ah cool, wasn't even aware Stylus didn't support non-standard @ rules. Will update today.

**Comment by corysimmons** [comment]
:+1:
