### ISSUE TITLE
poststylus and brunch?

### ISSUE THREAD

**Issue by ggerico** [seaneking/poststylus#18]
Any idea how to make them work together?

my brunch config file:

plugins: {
    elmBrunch: {
      elmFolder: 'web/elm',
      mainModules: ['SeatSaver.elm'],
      outputFolder: '../static/vendor'
    },
    babel: {
      // Do not use ES6 compiler in vendor code
      ignore: [/web\/static\/vendor/]
    },
    stylus: {
      plugins: ['jeet', poststylus(['autoprefixer', 'rucksack-css'])]
    },
  }

**Comment by seaneking** [comment]
Sorry not familiar with Brunch myself. I know `grunt-stylus` doesn't let you pass arguments to plugins, could be a similar scenario here? Just a hunch though.

**Comment by ggerico** [comment]
Yep, I had tried the Grunt's way, but the result was just the same.
I should say welcome to webpack ~
Anyway, thank you

**Comment by brooksdubois** [comment]
if anyone is still curious this is how I got it to work:
```
exports.overrides = {
	production: {
		optimize: true,
		sourceMaps: false,
		plugins: {
			stylus: {
				plugins: [ require('poststylus')(['autoprefixer', 'csswring']) ]
			}
		}
	}
}
```

**Comment by seaneking** [comment]
Excellent glad you found a solution @brooksdubois — closing this issue since it's solved with `stylus-brunch`
