### ISSUE TITLE
How to work with async postcss plugins?

### ISSUE THREAD

**Issue by edygar** [seaneking/poststylus#3]
I'm trying to solve the usage with [postcss-sprites](https://github.com/2createStudio/postcss-sprites) but so far I've no lucky, all I got was "Use process(css).then(cb) to work with async plugins"

**Comment by seaneking** [comment]
hrmm, haven't worked with async plugins before. I'll look into this and patch it soon. Might have to add an `async: true` option.

**Comment by edygar** [comment]
+1

If there's anything I can help, let me know

**Comment by seaneking** [comment]
Okay so I've been messing around with getting this to work, but unfortunately Stylus' `end` event doesn't accept a callback, meaning that there's no way to pass the result of asynchronous PostCSS plugins back to Stylus after processing. So until https://github.com/stylus/stylus/issues/1698 is fixed, there's nothing I can do. I'll put the work I've done so far on this up in a branch and keep an eye on that issue, but it's from sept 2014 and hasn't had any activity, so don't have high hopes, and I don't really have time to go hacking around the Stylus codebase myself.
