### ISSUE TITLE
Usage of a local postcss plugin

### ISSUE THREAD

**Issue by cakeinpanic** [seaneking/poststylus#4]
If I want to run `poststylus` by CLI and use my local plugin from `index.js` from the project root, what should I pass as a parameter?
Is it possible?

**Comment by seaneking** [comment]
Yep should be pretty straightforward, pass poststylus to `use` and the full dir path to your plugin file to `with`. Then just export the plugin in `index.js` as you would any other js module.

So running the stylus CLI tool from your working dir, it might look something like this
```bash
$ stylus --use ./node_modules/poststylus --with "[require('${PWD}/index.js)()" --out test.css < test.styl
```
