### ISSUE TITLE
Using with grunt-contrib-stylus?

### ISSUE THREAD

**Issue by kezzbracey** [seaneking/poststylus#6]
Hey Sean,

Thanks for this module!

I've been able to get the setup going with Gulp super easily, however I'm a bit stumped on getting it going with Grunt. (I'm doing both as I'm writing a tutorial showing users of both how to setup poststylus)

I'm using grunt-contrib-stylus and first attempted following the Gruntfile structure in the readme, but didn't manage to get a successful compile.

This is the furthest I've been able to get without errors:

```
module.exports = function(grunt) {

  grunt.initConfig({

    stylus: {
      compile: {
        options: {
          use: [
            require('poststylus')
          ]
        },
        files: {
          'dest/style.css': 'src/style.styl'
        }
      }
    }

  });

  grunt.loadNpmTasks('grunt-contrib-stylus');

};
```

However as soon as I start to try adding plugin names it fails, which I attempted via:

    require('poststylus')('autoprefixer', 'cssnano')

I'm not a big Grunt user so I'm not sure if it's my Gruntfile, something on the grunt-contrib-stylus end, or something to do with the new PostCSS api.

If you have any insights on how I might get this going that would be super helpful.

Thanks!

**Comment by seaneking** [comment]
Hrmm. I'm not a big Grunt user either - what's in your error logs?

**Comment by seaneking** [comment]
Oh sorry just saw, in your example the `require()` isn't being passed an array. ie: should look like `require('poststylus')(['autoprefixer', 'cssnano'])`

**Comment by kezzbracey** [comment]
Thanks for the quick feedback Sean, I appreciate that.

Sorry that was actually a silly typo on my part, I did try passing them via an array. Even with the [] added, it seems to stop the JSON being parsed for some reason judging by the warning message I get:

```
Warning: Cannot read property 'options' of undefined Use --force to continue.

Aborted due to warnings.
```

The stylus task does run if the use: [] array is empty though.

Have you found you've been able to get a Grunt compile running with the current versions of everything? If so, perhaps I could bother you for a Gruntfile?

**Comment by seaneking** [comment]
Ah okay, I'll have to spin things up locally and see what's going on. Will look into it soon.

**Comment by kezzbracey** [comment]
Thanks very much! Btw the tutorial will be going up on webdesign.tutsplus.com - I can ping you when it's up if you'd like.

**Comment by seaneking** [comment]
Okay so it looks like you can't pass arguments to `require()` with grunt-contrib-stylus because it expects a function to be returned for plugins , so unfortunately you'd have to wrap poststylus in another function and return it.

So it'd look more like this:

```
 stylus: {
      compile: {
        options: {
          use: [
            function() {
               return require('poststylus')(['rucksack-css'])
              }
          ]
        },
        files: {
          'dest/style.css': 'src/style.styl'
        }
      }
    }
```

Though it'd probably make more sense to declare that in a `var` at the top of the file and just pass that to the grunt task, to keep things from getting too messy. I'll update the docs now. Really should have tested this more thoroughly in person before chucking it in the docs, derp.

And would love to have a read of your tute when it's up, thanks!

**Comment by kezzbracey** [comment]
Perfect, that worked beautifully. Thanks!

**Comment by kezzbracey** [comment]
Oh btw, you might need this line for your readme:

`grunt.loadNpmTasks('grunt-contrib-stylus');`

...rather than:

`grunt.registerTask('default', ['stylus']);`

**Comment by seaneking** [comment]
derp.. again. You can tell I'm not a grunt user. All fixed. Thanks!
