### ISSUE TITLE
problem with rucksack compile

### ISSUE THREAD

**Issue by kangw3n** [seaneking/poststylus#7]
Hi there,

I'm currently using rucksack + stylus as my css development, but i found that there is a problem after compiling my rucksack code.

For example, my rucksack stylus code:
```
p
  font-size responsive 
```

it turns out :
```
@media screen and (min-width: 1280px) {
  p {
    font-size: 21px;
  }
}

p {
  font-size: calc((12px - 420px * 0.010465116279069767) + 1.0465116279069768vw);
}

@media screen and (max-width: 420px) {
  p {
    font-size: 12px;
  }
}
```

This will cause an old school css specificity problem where font-size 21px will be replace by font-size calc()....no matter the specify breakpoint reach or not. which not what we wanted.

p/s. : I've try using rucksack own CLI to compile and it will produce the correct order of code.

Thanks in advance.

**Comment by seaneking** [comment]
That's very unusual. I'm using PostStylus on the Rucksack site itself (http://simplaio.github.io/rucksack) and responsive type is working fine and outputting rules in the correct order. Can you give me some more info about your env - what build tool are you running, what other postcss plugins are you using, etc.

**Comment by kangw3n** [comment]
Hi 

I'm using gulp and I've just tested it in a new and completely blank env, here is my gulp dependencies:

```
    "gulp": "^3.9.0",
    "gulp-load-plugins": "^1.0.0-rc.1",
    "gulp-stylus": "^2.0.6",
    "poststylus": "^0.2.1",
    "rucksack-css": "^0.6.7"
```

and my gulpjs task as below:
```
var gulp = require('gulp');
var $ = require('gulp-load-plugins')({ lazy: true });
var poststylus = require('poststylus');

gulp.task('stylus', function() {
  return gulp
    .src('base.styl')
    .pipe($.stylus({
      use: [
        poststylus(['rucksack-css']),
      ]
    }))
    .pipe(gulp.dest('./'));
});
```

and it again outputting in the order as I mention in 1st post
gulp version : CLI 3.8.11 , Local 3.9.0
node version : 0.12.4

hope it will replicate the problem for you?

Thanks

**Comment by seaneking** [comment]
gah sorry I still haven't gotten around to testing this. Are you still having the issue with the latest Rucksack? I can only assume it's something to do with `gulp-load-plugins` and lazy-loading, have you tried without gulp-load-plugins and/or lazy-loading?

**Comment by seaneking** [comment]
Okay managed to replicate this - it's an issue with `postcss-responsive-type` (the raw module that does responsive type in Rucksack), not poststylus. I didn't realise that a PostCSS method I was using (`insertAfter`) was asynchronous, so if you have a lot of responsive type declarations the media queries can get mixed up. Fixed in https://github.com/seaneking/postcss-responsive-type/commit/a6a8a46d2e102af3408b0a92abaedbc6fe062e1e
