### ISSUE TITLE
Meteor plugin

### ISSUE THREAD

**Issue by alexschomb** [seaneking/poststylus#8]
Thank you for creating PostStylus.

I plan to create a Meteor project using the [LostGrid CSS framework](https://github.com/corysimmons/lost). If I understood correctly, the only way to use current versions of ``lost`` with Stylus is via PostCSS/PostStylus. I couldn't find any Meteor package for PostStylus on [AtmosphereJS](https://atmospherejs.com). Is there any chance you'll provide a package in the future?

**Comment by seaneking** [comment]
I've never used meteor, so probably not no. 

Again, not familiar with how things work in meteor land, but surely you can just add PostCSS to your build tool and call it a day? Or even just process your CSS on the command line?
